#!/system/bin/sh
PLGP=/sdcard/plugin
PLGBP=/sdcard/plugin/.bin
CMDIN=/tmp/cmdin.tmp
CMD1="test -f /sdcard/plugin/AutoInstaller.tar.gz && busybox tar zxf /sdcard/plugin/AutoInstaller.tar.gz -C /mnt/plugin && chmod 777 /mnt/plugin/AutoInstaller* 2>&1 >/dev/null"

test ! -f /sdcard/AIP.tar && ERR=false && echo "File not exists : /sdcard/AIP.tar ." 
test ! -f /sdcard/IAP.tar && ERR=false && echo "File not exists : /sdcard/IAP.tar ."

test -f /sdcard/AIP.tar && busybox tar xf /sdcard/AIP.tar -C /mnt/plugin
test -f /mnt/plugin/AutoInstaller && chmod 777 /mnt/plugin/AutoInstaller* 2>&1 >/dev/null

test -f /sdcard/APG.tar && rm -f /sdcard/APG.tar
test -f /sdcard/APG.tar.gz && rm -f /sdcard/APG.tar.gz
test -f /sdcard/0_AutoPlugin_Install && rm -f /sdcard/0_AutoPlugin_Install
test -d $PLGP && rm -fr $PLGP 2>&1 >/dev/null
test ! -d $PLGBP && mkdir -p $PLGBP $PLGBP/Plugins $PLGBP/ArchivedPlugins

rm -f /data/data/sites.mjwhitta.scripter/files/* 2>&1 >/dev/null
rm -f /data/data/sites.mjwhitta.scripter/files/.bin* 2>&1 >/dev/null

for S in "1_Install_Reinstall_AutoInstaller:$CMD1:'AutoInstaller will install or reinstall.'" \
	"2_Upgrade_AutoInstaller:upgrade:'AutoInstaller will upgrade to new version.'" \
	"3_Start_FTP_service:run-services start:''" \
	 "4_Stop_FTP_service:run-services stop:'Services stoped.'" \
	 "5_AutoPlugin_Local_Install:plugin-install:'Local plugins will install. Please check from plugin section.'" \
	 "6_AutoPlugin_UpdateList:plugin-update-list:'Plugins list will update. Use AutoPlugin_ShowList to view them.'" \
	 "7_AutoPlugin_UpdateArchiveList:plugin-update-archivelist:'Archive plugins list will updat. Use AutoPlugin_ShowAList to view them.'"
	do
SNAME=$(echo $S|cut -d':' -f1)
SCMD=$(echo $S|cut -d':' -f2)
SMSG=$(echo $S|cut -d':' -f3)
echo "#!/system/bin/sh\necho '$SCMD' >$CMDIN\necho $SMSG" >$PLGBP/$SNAME
if [ "$SNAME" = "1_Install_Reinstall_AutoInstaller" ] ; then echo "#!/system/bin/sh\n$SCMD\necho $SMSG" >$PLGBP/$SNAME ; fi
if [ "$SNAME" = "3_Start_FTP_service" ] ;then echo "#!/system/bin/sh\nIP=\$(ip route|cut -d' ' -f12)\necho '$SCMD' >$CMDIN\necho \"Services started on :\n\t\t\t\t\t\t\$IP:1021\"">$PLGBP/$SNAME;fi
done

echo "#!/system/bin/sh\necho '$PLGBP/Plugins' > /data/data/sites.mjwhitta.scripter/files/script_paths">$PLGBP/8_AutoPlugin_ShowList
echo "#!/system/bin/sh\necho '$PLGBP/ArchivedPlugins' > /data/data/sites.mjwhitta.scripter/files/script_paths">$PLGBP/9_AutoPlugin_ShowArchiveList
echo "echo 'scripter restart'>$CMDIN">>$PLGBP/8_AutoPlugin_ShowList
echo "echo 'scripter restart'>$CMDIN">>$PLGBP/9_AutoPlugin_ShowArchiveList

echo "#!/system/bin/sh\necho $PLGBP > /data/data/sites.mjwhitta.scripter/files/script_paths">$PLGBP/Plugins/0_Show_Main_Menu
echo "echo 'scripter restart'>$CMDIN">>$PLGBP/Plugins/0_Show_Main_Menu
cp $PLGBP/Plugins/0_Show_Main_Menu $PLGBP/ArchivedPlugins/0_Show_Main_Menu

for f in  ArchivedPlugins_0_Show_Main_Menu Plugins_0_Show_Main_Menu .bin_8_AutoPlugin_ShowList .bin_9_AutoPlugin_ShowArchiveList
do echo '0\n\n1' >>/data/data/sites.mjwhitta.scripter/files/$f ; done

test -f $PLGBP/README.md && rm -f $PLGBP/README.md
test ! -f $PLGBP/README.md && busybox tail -30 $0 >$PLGBP/README.md
echo "#!/system/bin/sh\ncat $PLGBP/README.md" >$PLGBP/0_About_AutoInstaller

echo $PLGBP > /data/data/sites.mjwhitta.scripter/files/script_paths
echo "Insatallation complete successful. Please Close \$cripter app and run plugin , then start AutoInstaller plugin."
exit

# Icone-Iron-AutoInstaller
## By Farhamxp <farhamxp@gamil.com>
Project Home :https://github.com/IronAutoPlugin
Project News channel : <https://t.me/IronAutoPlugin>   
Installation files and Guide : <https://github.com/IronAutoPlugin/AutoInstaller>
  
### Thechnical Info : <https://github.com/IronAutoPlugin/Iron-Plugins/wiki>
   
Note : This repository has two branchs.
Plugins branch has the last version of each plugin and   
ArchivedPlugin branch has Archives of plugins.
#### These Plugins used in AutoPlugin scripts. It download and install plugins directly from this repository.    
### All plugins uploaded or maked by dear Mohammad Nasr and other friends.

If everyone wants to create new fork of this repository, it's not problem. But that's fork unusable in AutoPlugin.  
Dear plugin creators : If your output files maked with Thechnical Info structure, that,s usable with AutoPlugin.  
Please tell me to share them with other Icone iron users.  

## License:   
AutoPlugin is licensed under the GNU General Public License (GPL).  This means that is "free software".  
That is, not only can AutoPlugin be downloaded and used at no cost, its source code is also available to be analyzed, modified, and contributed to.  
For more information on the GNU GPL see the GNU website here.<http://www.gnu.org/licenses/gpl-3.0.txt>

## Credits:  
The basic concept of these credits is that the collaborative nature of open-source community has allowed myself to making AutoPluginas a very nice tool.  
  
## SPECIAL THANKS TO SPECIAL PEOPLE :  
### Shahab(t.me/Sky4533)  
### Miles Whittaker (mjwhitta) <https://mj.whitta.dev>
### Mohammad Nasr (MNASR,popking159) <https://oscambinaries.blogspot.com>
