#!/system/bin/sh
# By farhamxp for icone
Ver=3.3
INSTALLER=AutoInstaller_Install
PLGC=/sdcard/AutoInstaller/cache
PLGI=/sdcard/AutoInstaller/install
SUMU="https://raw.githubusercontent.com/IronAutoPlugin/AutoInstaller/master/install/cksum"
U1="https://raw.githubusercontent.com/IronAutoPlugin/AutoInstaller/master/install/AutoInstaller_Install"
U2="https://raw.githubusercontent.com/IronAutoPlugin/AutoInstaller/master/install/AIP.tar"
U3="https://raw.githubusercontent.com/IronAutoPlugin/AutoInstaller/master/install/IAP.tar"

if [ ! -f /sdcard/AutoUninstaller ] ; then 
echo "#!/system/bin/sh\npkill run.sh\nsed -i '/\/data\/iap\/run\.sh \&/d' /data/plugin/autorun.sh\npkill run.sh\nrm -fr /data/iap\nrm -f /data/data/sites.mjwhitta.scripter/files/*\nrm -f /data/plugin/AutoUninstaller*\ndate>/sdcard/AutoUninstaller">/mnt/plugin/AutoUninstaller
chmod +x /mnt/plugin/AutoUninstaller
echo "Please Start AutoUninstaller on plugins. After deleting AutoUninstaller plugin, run AutoInstaller_download again."
exit ; fi

test ! -d $PLGC && mkdir -p $PLGC
if [ -d $PLGI ] ; then cd $PLGI ; cksum *.tar AutoInstaller_Install|sed '/gz$/d'|sort -d -k 3,3 >cksum ; fi
test ! -d $PLGI && mkdir -p $PLGI && touch $PLGI/cksum


curl -Lks --connect-timeout 5 $SUMU -o $PLGC/cksum
DIFF=$(busybox diff $PLGI/cksum $PLGC/cksum|wc -c)
if [ $DIFF != 0 ] ; then
curl -Lks --connect-timeout 5 $U1 -o $PLGI/AutoInstaller_Install
curl -Lks --connect-timeout 5 $U2 -o $PLGI/AIP.tar
curl -Lks --connect-timeout 5 $U3 -o $PLGI/IAP.tar
fi
sh $PLGI/$INSTALLER
mv $0 $PLGI